#pragma once
//IOCTL宏
#define BASE_CODE 0X800
#define MAKE_CODE_BUFFER(i)  CTL_CODE(FILE_DEVICE_UNKNOWN, BASE_CODE + i, METHOD_BUFFERED , FILE_ANY_ACCESS)
//METHOD_IN_DIRECT和METHOD_OUT_DIRECT二选一，处理方式都可以是一样的。
#define MAKE_CODE_DIRECT(i)  CTL_CODE(FILE_DEVICE_UNKNOWN, BASE_CODE + i, METHOD_IN_DIRECT, FILE_ANY_ACCESS)	
#define MAKE_CODE_NEITHER(i) CTL_CODE(FILE_DEVICE_UNKNOWN, BASE_CODE + i, METHOD_NEITHER  , FILE_ANY_ACCESS)

#define FG_HELLO1 MAKE_CODE_BUFFER(0)
#define FG_HELLO2 MAKE_CODE_DIRECT(1)
#define FG_HELLO3 MAKE_CODE_NEITHER(2)